### ISSUE TITLE
architect build should have a switch for pushing images

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/architect#157]

**Comment by webwurst** [comment]
Would this solve the following?
```
architect build
```
```
2017/10/18 16:27:58 could not fetch workflow: empty docker username
```

**Comment by oponder** [comment]
I need this flag so I can enable forked pull requests on Happa.

I want to build but not push for forked pull requests, since pushes will fail without our secrets in the ENV.

Happy to take a try at the implementation.

@JosephSalisbury how does something like `architect build --no-push` sound to you?

**Comment by JosephSalisbury** [comment]
Alternatively, we can be a bit clever and not try to push if the credentials aren't present (as I assume they wouldn't be for forked pull requests).
